export enum ErrorsCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SAME_EMAIL_ALREADY_EXISTS = 'ORG_SAME_EMAIL_ALREADY_EXISTS',
  AVATAR_NO_SET = 'AVATAR_NO_SET',
  RESOURCE_NOT_FOUND_ERROR = 'RESOURCE_NOT_FOUND_ERROR',
  OLD_PASSWORD_DOES_NOT_MATCH = 'OLD_PASSWORD_DOES_NOT_MATCH',
  NEW_PASSWORD_DOES_NOT_MATCH = 'NEW_PASSWORD_DOES_NOT_MATCH',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  MISSING_MANDATORY_DATA = 'MISSING_MANDATORY_DATA',
  MAX_NUMBER_OF_MOOD_TYPE_REACHED = 'MAX_NUMBER_OF_MOOD_TYPE_REACHED',
  MISSING_TOKEN_OR_EXPIRATION_TIME = 'MISSING_TOKEN_OR_EXPIRATION_TIME',
}
